id: I81FBBB09
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:20:22+00:00'
last_modified: '2022-06-08T08:20:08.745960+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17558
  title: རྗེ་བློ་གསལ་ཚང་གི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EFD4:
      image_group_id: I8LS17570
      title: ''
      total_pages: 202
      order: 1
      base_file: EFD4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
